name: CI/CD

on:
    release:
        branches: -master
    push:
        branches:
            - master
            - gh-actions
    pull_request:
        branches:
            - master
            - gh-actions

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Explain why this job ran
              uses: monacorp/action-name@master
              with:
                  entrypoint: /bin/echo
                  args: The ${{ github.event_name }} event triggered this action.

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              run: npm i

            - name: Run the tests and generate coverage report
              run: npm run cov:actions
              env:
                  UBI_USER: ${{ secrets.UBI_USER }}
                  UBI_PW: ${{ secrets.UBI_PW }}
                  TM_ID: ${{ secrets.TM_ID }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1

            - name: Build docs
              run: npm run doc:html

            - name: Deploy to netlify
              if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
            - uses: jsmrcaga/action-netlify-deploy@master
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_MESSAGE: 'Preview deploy v${{ github.ref }}'
                  build_directory: 'build/docs'

            - name: Deploy to netlify
              if: ${{ github.event_name == 'release' }}
            - uses: jsmrcaga/action-netlify-deploy@master
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_MESSAGE: 'Production deploy v${{ github.ref }}'
                  NETLIFY_DEPLOY_TO_PROD: true
                  build_directory: 'build/docs'
